### ISSUE TITLE
results diffrence

### ISSUE THREAD

**Issue by jaydetang** [hadi-abdine/Prot2Text#1]
Hello, thanks for your outstanding work, but I am wondering what you did to improve the results compared to version 1 of
the paper on Arxiv.

**Comment by hadi-abdine** [comment]
Hello, thanks for your interest in our work.

Actually, in the first version of the code (v1 on arxiv), some hyperparameters for text generation using huggingface transformers library were set from a tutorial on text generation. In the new version, we just removed those hyperparameters and used the default values since there is no justification of using different ones.
Even though the results  improved, the conclusion and the analysis remain the same since the improvement was made on all the models in the study.
You can re-obtain the same results of Table 1 in v1 of the paper  by only adding the following arguments to the generate function in the `evaluate_prot2text.py`:
- `early_stopping=True`
- `no_repeat_ngram_size=3`
- `length_penalty=2.0`
